# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - main: ./cmd/
    env:
      - CGO_ENABLED=0
    goarm:
      - 6
      - 7
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: android
        goarch: arm
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: android
        goarch: 386
archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
    - goos: windows
      format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - README.md
      - README.zh.md
release:
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
project_name: mlcgo
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'